# Generated by Django 2.0.3 on 2018-03-23 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[
                 django.core.validators.RegexValidator(
                     '^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(
                    blank=True, max_length=2048, null=True)),
                ('link', models.URLField(max_length=1024)),
                ('scoring_strategy', models.TextField(
                    blank=True, max_length=1028, null=True)),
            ],
        ),
    ]
