# Generated by Django 2.0.5 on 2018-08-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
