# Generated by Django 2.0.3 on 2018-04-09 15:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180409_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='scoring_strategy',
        ),
        migrations.AddField(
            model_name='board',
            name='strategy_params',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='strategy_py_module',
            field=models.CharField(default='my_little_ticket.plugins.default.DefaultStrategy', max_length=255),
            preserve_default=False,
        ),
    ]
