# Generated by Django 2.0.3 on 2018-04-09 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20180409_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
